apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: default
spec:
  secretName: s{{ .Values.certificate.secretName }}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - {{ .Values.certificate.organizations }}
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ .Values.domain }}
  issuerRef:
    name: {{ .Values.issuer.name }}
    kind: ClusterIssuer
    group: cert-manager.io
